(in-package :clode.def)


(defpackage :%clode.utils
  (:use :cl :alexandria)
  (:export defanonenum
           lispify))


(defpackage :clode
  (:nicknames :ode)
  (:use :%clode.utils)
  (:export
   :ode-version
   :geom-tri-mesh-data-update
   :geom-tri-mesh-get-triangle-count
   :geom-tri-mesh-get-point
   :geom-tri-mesh-get-triangle
   :geom-tri-mesh-get-tri-mesh-data-id
   :geom-tri-mesh-clear-tccache
   :geom-tri-mesh-is-tcenabled
   :geom-tri-mesh-enable-tc
   :geom-tri-mesh-get-data
   :geom-tri-mesh-set-data
   :create-tri-mesh
   :geom-tri-mesh-get-tri-merge-callback
   :geom-tri-mesh-set-tri-merge-callback
   :tri-tri-merge-callback
   :geom-tri-mesh-get-ray-callback
   :geom-tri-mesh-set-ray-callback
   :tri-ray-callback
   :geom-tri-mesh-get-array-callback
   :geom-tri-mesh-set-array-callback
   :tri-array-callback
   :geom-tri-mesh-get-callback
   :geom-tri-mesh-set-callback
   :tri-callback
   :geom-tri-mesh-data-set-buffer
   :geom-tri-mesh-data-get-buffer
   :geom-tri-mesh-data-preprocess
   :geom-tri-mesh-data-build-simple1
   :geom-tri-mesh-data-build-simple
   :geom-tri-mesh-data-build-double1
   :geom-tri-mesh-data-build-double
   :geom-tri-mesh-data-build-single1
   :geom-tri-mesh-data-build-single
   :geom-tri-mesh-get-last-transform
   :geom-tri-mesh-set-last-transform
   :geom-tri-mesh-data-get
   :geom-tri-mesh-data-set
   :trimesh-face-normals
   :geom-tri-mesh-data-destroy
   :geom-tri-mesh-data-create
   :tri-mesh-data-id
   :set-collider-override
   :create-geom
   :geom-get-class-data
   :create-geom-class
   :geom-class
   :tor
   :aabb-test
   :aabb
   :collider
   :bytes
   :geom-class
   :aabbtest-fn
   :geom-dtor-fn
   :get-collider-fn-fn
   :collider-fn
   :get-aabbfn
   :infinite-aabb
   :box-box
   :box-touches-box
   :closest-line-segment-points
   :geom-heightfield-get-heightfield-data
   :geom-heightfield-set-heightfield-data
   :geom-heightfield-data-set-bounds
   :geom-heightfield-data-build-double
   :geom-heightfield-data-build-single
   :geom-heightfield-data-build-short
   :geom-heightfield-data-build-byte
   :geom-heightfield-data-build-callback
   :geom-heightfield-data-destroy
   :geom-heightfield-data-create
   :create-heightfield
   :heightfield-get-height
   :heightfield-data-id
   :geom-transform-get-info
   :geom-transform-set-info
   :geom-transform-get-cleanup
   :geom-transform-set-cleanup
   :geom-transform-get-geom
   :geom-transform-set-geom
   :create-geom-transform
   :geom-ray-get-closest-hit
   :geom-ray-set-closest-hit
   :geom-ray-get-backface-cull
   :geom-ray-set-backface-cull
   :geom-ray-get-first-contact
   :geom-ray-set-first-contact
   :geom-ray-get-params
   :geom-ray-set-params
   :geom-ray-get
   :geom-ray-set
   :geom-ray-get-length
   :geom-ray-set-length
   :create-ray
   :geom-cylinder-get-params
   :geom-cylinder-set-params
   :create-cylinder
   :geom-capsule-point-depth
   :geom-capsule-get-params
   :geom-capsule-set-params
   :create-capsule
   :geom-plane-point-depth
   :geom-plane-get-params
   :geom-plane-set-params
   :create-plane
   :geom-box-point-depth
   :geom-box-get-lengths
   :geom-box-set-lengths
   :create-box
   :geom-set-convex
   :create-convex
   :geom-sphere-point-depth
   :geom-sphere-get-radius
   :geom-sphere-set-radius
   :create-sphere
   :geom-num-classes
   :last-user-class
   :first-user-class
   :last-space-class
   :quad-tree-space-class
   :sweep-and-prune-space-class
   :hash-space-class
   :simple-space-class
   :first-space-class
   :heightfield-class
   :tri-mesh-class
   :geom-transform-class
   :convex-class
   :ray-class
   :plane-class
   :cylinder-class
   :capsule-class
   :box-class
   :sphere-class
   :max-user-classes
   :space-collide2
   :space-collide
   :collide
   :contacts-unimportant
   :geom-get-offset-quaternion
   :geom-copy-offset-rotation
   :geom-get-offset-rotation
   :geom-copy-offset-position
   :geom-get-offset-position
   :geom-is-offset
   :geom-clear-offset
   :geom-set-offset-world-quaternion
   :geom-set-offset-world-rotation
   :geom-set-offset-world-position
   :geom-set-offset-quaternion
   :geom-set-offset-rotation
   :geom-set-offset-position
   :geom-vector-from-world
   :geom-vector-to-world
   :geom-get-pos-rel-point
   :geom-get-rel-point-pos
   :geom-low-level-control
   :geom-collider-merge-contacts-value-full
   :geom-collider-merge-contacts-value-normals
   :geom-collider-merge-contacts-value-none
   :geom-collider-merge-contacts-value--default
   :geom-collider-get-merge-sphere-contacts-control-code
   :geom-collider-set-merge-sphere-contacts-control-code
   :geom-common-any-control-code
   :geom-collider-control-class
   :geom-common-control-class
   :geom-is-enabled
   :geom-disable
   :geom-enable
   :geom-get-collide-bits
   :geom-get-category-bits
   :geom-set-collide-bits
   :geom-set-category-bits
   :geom-get-class
   :geom-get-space
   :geom-is-space
   :geom-get-aabb
   :geom-get-quaternion
   :geom-copy-rotation
   :geom-get-rotation
   :geom-copy-position
   :geom-get-position
   :geom-set-quaternion
   :geom-set-rotation
   :geom-set-position
   :geom-get-body
   :geom-set-body
   :geom-get-data
   :geom-set-data
   :geom-destroy
   :space-get-class
   :space-get-geom
   :space-get-num-geoms
   :space-clean
   :space-query
   :space-remove
   :space-add
   :space-get-manual-cleanup
   :space-set-manual-cleanup
   :space-get-sublevel
   :space-set-sublevel
   :space-get-cleanup
   :space-set-cleanup
   :hash-space-get-levels
   :hash-space-set-levels
   :space-destroy
   :sweep-and-prune-space-create
   :sap-axes-zyx
   :sap-axes-zxy
   :sap-axes-yzx
   :sap-axes-yxz
   :sap-axes-xzy
   :sap-axes-xyz
   :quad-tree-space-create
   :hash-space-create
   :simple-space-create
   :near-callback
   :are-connected-excluding
   :are-connected
   :connecting-joint-list
   :connecting-joint
   :joint-get-dhinge-param
   :joint-set-dhinge-param
   :joint-get-dhinge-distance
   :joint-get-dhinge-anchor2
   :joint-get-dhinge-anchor1
   :joint-set-dhinge-anchor2
   :joint-set-dhinge-anchor1
   :joint-get-dhinge-axis
   :joint-set-dhinge-axis
   :joint-get-dball-param
   :joint-set-dball-param
   :joint-set-dball-distance
   :joint-get-dball-distance
   :joint-get-dball-anchor2
   :joint-get-dball-anchor1
   :joint-set-dball-anchor2
   :joint-set-dball-anchor1
   :joint-set-transmission-backlash
   :joint-get-transmission-backlash
   :joint-set-transmission-radius2
   :joint-set-transmission-radius1
   :joint-get-transmission-radius2
   :joint-get-transmission-radius1
   :joint-get-transmission-angle2
   :joint-get-transmission-angle1
   :joint-get-transmission-axis
   :joint-set-transmission-axis
   :joint-get-transmission-ratio
   :joint-set-transmission-ratio
   :joint-get-transmission-mode
   :joint-set-transmission-mode
   :joint-get-transmission-param
   :joint-set-transmission-param
   :joint-get-transmission-anchor2
   :joint-set-transmission-anchor2
   :joint-get-transmission-anchor1
   :joint-set-transmission-anchor1
   :joint-get-transmission-axis2
   :joint-set-transmission-axis2
   :joint-get-transmission-axis1
   :joint-set-transmission-axis1
   :joint-get-transmission-contact-point2
   :joint-get-transmission-contact-point1
   :joint-get-fixed-param
   :joint-get-lmotor-param
   :joint-get-lmotor-axis
   :joint-get-lmotor-num-axes
   :joint-get-amotor-mode
   :joint-get-amotor-param
   :joint-get-amotor-angle-rate
   :joint-get-amotor-angle
   :joint-get-amotor-axis-rel
   :joint-get-amotor-axis
   :joint-get-amotor-num-axes
   :joint-get-piston-param
   :joint-get-piston-axis
   :joint-get-piston-anchor2
   :joint-get-piston-anchor
   :joint-get-piston-angle-rate
   :joint-get-piston-angle
   :joint-get-piston-position-rate
   :joint-get-piston-position
   :joint-get-puparam
   :joint-get-puangle2-rate
   :joint-get-puangle2
   :joint-get-puangle1-rate
   :joint-get-puangle1
   :joint-get-puangles
   :joint-get-puaxis-p
   :joint-get-puaxis3
   :joint-get-puaxis2
   :joint-get-puaxis1
   :joint-get-puposition-rate
   :joint-get-puposition
   :joint-get-puanchor
   :joint-get-prparam
   :joint-get-praxis2
   :joint-get-praxis1
   :joint-get-prangle-rate
   :joint-get-prangle
   :joint-get-prposition-rate
   :joint-get-prposition
   :joint-get-pranchor
   :joint-get-universal-angle2-rate
   :joint-get-universal-angle1-rate
   :joint-get-universal-angle2
   :joint-get-universal-angle1
   :joint-get-universal-angles
   :joint-get-universal-param
   :joint-get-universal-axis2
   :joint-get-universal-axis1
   :joint-get-universal-anchor2
   :joint-get-universal-anchor
   :joint-get-hinge2-angle2-rate
   :joint-get-hinge2-angle1-rate
   :joint-get-hinge2-angle2
   :joint-get-hinge2-angle1
   :joint-get-hinge2-param
   :joint-get-hinge2-axis2
   :joint-get-hinge2-axis1
   :joint-get-hinge2-anchor2
   :joint-get-hinge2-anchor
   :joint-get-slider-param
   :joint-get-slider-axis
   :joint-get-slider-position-rate
   :joint-get-slider-position
   :joint-get-hinge-angle-rate
   :joint-get-hinge-angle
   :joint-get-hinge-param
   :joint-get-hinge-axis
   :joint-get-hinge-anchor2
   :joint-get-hinge-anchor
   :joint-get-ball-param
   :joint-get-ball-anchor2
   :joint-get-ball-anchor
   :joint-set-plane2-dangle-param
   :joint-set-plane2-dyparam
   :joint-set-plane2-dxparam
   :joint-set-lmotor-param
   :joint-set-lmotor-axis
   :joint-set-lmotor-num-axes
   :joint-add-amotor-torques
   :joint-set-amotor-mode
   :joint-set-amotor-param
   :joint-set-amotor-angle
   :joint-set-amotor-axis
   :joint-set-amotor-num-axes
   :joint-set-fixed-param
   :joint-set-fixed
   :joint-add-piston-force
   :joint-set-piston-param
   :joint-set-piston-axis-delta
   :joint-set-piston-axis
   :joint-set-piston-anchor-offset
   :joint-set-piston-anchor
   :joint-add-putorque
   :joint-set-puparam
   :joint-set-puaxis-p
   :joint-set-puaxis3
   :joint-set-puaxis2
   :joint-set-puaxis1
   :joint-set-puanchor-offset
   :joint-set-puanchor-delta
   :joint-set-puanchor
   :joint-add-prtorque
   :joint-set-prparam
   :joint-set-praxis2
   :joint-set-praxis1
   :joint-set-pranchor
   :joint-add-universal-torques
   :joint-set-universal-param
   :joint-set-universal-axis2-offset
   :joint-set-universal-axis2
   :joint-set-universal-axis1-offset
   :joint-set-universal-axis1
   :joint-set-universal-anchor
   :joint-add-hinge2-torques
   :joint-set-hinge2-param
   :joint-set-hinge2-axis2
   :joint-set-hinge2-axis1
   :joint-set-hinge2-anchor
   :joint-add-slider-force
   :joint-set-slider-param
   :joint-set-slider-axis-delta
   :joint-set-slider-axis
   :joint-add-hinge-torque
   :joint-set-hinge-param
   :joint-set-hinge-axis-offset
   :joint-set-hinge-axis
   :joint-set-hinge-anchor-delta
   :joint-set-hinge-anchor
   :joint-set-ball-param
   :joint-set-ball-anchor2
   :joint-set-ball-anchor
   :joint-get-feedback
   :joint-set-feedback
   :joint-get-body
   :joint-get-type
   :joint-get-data
   :joint-set-data
   :joint-is-enabled
   :joint-disable
   :joint-enable
   :joint-attach
   :joint-get-num-bodies
   :joint-group-empty
   :joint-group-destroy
   :joint-group-create
   :joint-destroy
   :joint-create-transmission
   :joint-create-dhinge
   :joint-create-dball
   :joint-create-plane-2d
   :joint-create-lmotor
   :joint-create-amotor
   :joint-create-null
   :joint-create-fixed
   :joint-create-piston
   :joint-create-pu
   :joint-create-pr
   :joint-create-universal
   :joint-create-hinge2
   :joint-create-contact
   :joint-create-slider
   :joint-create-hinge
   :joint-create-ball
   :body-set-gyroscopic-mode
   :body-get-gyroscopic-mode
   :body-set-max-angular-speed
   :body-get-max-angular-speed
   :body-set-angular-damping-threshold
   :body-get-angular-damping-threshold
   :body-set-linear-damping-threshold
   :body-get-linear-damping-threshold
   :body-set-damping
   :body-set-angular-damping
   :body-get-angular-damping
   :body-set-linear-damping
   :body-get-linear-damping
   :body-set-damping-defaults
   :body-get-next-geom
   :body-get-first-geom
   :body-set-moved-callback
   :body-get-gravity-mode
   :body-set-gravity-mode
   :body-is-enabled
   :body-disable
   :body-enable
   :body-is-kinematic
   :body-set-kinematic
   :body-set-dynamic
   :body-get-joint
   :body-get-num-joints
   :body-get-finite-rotation-axis
   :body-get-finite-rotation-mode
   :body-set-finite-rotation-axis
   :body-set-finite-rotation-mode
   :body-vector-from-world
   :body-vector-to-world
   :body-get-pos-rel-point
   :body-get-point-vel
   :body-get-rel-point-vel
   :body-get-rel-point-pos
   :body-set-torque
   :body-set-force
   :body-get-torque
   :body-get-force
   :body-add-rel-force-at-rel-pos
   :body-add-rel-force-at-pos
   :body-add-force-at-rel-pos
   :body-add-force-at-pos
   :body-add-rel-torque
   :body-add-rel-force
   :body-add-torque
   :body-add-force
   :body-get-mass
   :body-set-mass
   :body-get-angular-vel
   :body-get-linear-vel
   :body-copy-quaternion
   :body-get-quaternion
   :body-copy-rotation
   :body-get-rotation
   :body-copy-position
   :body-get-position
   :body-set-angular-vel
   :body-set-linear-vel
   :body-set-quaternion
   :body-set-rotation
   :body-set-position
   :body-get-data
   :body-set-data
   :body-destroy
   :body-create
   :body-get-world
   :body-set-auto-disable-defaults
   :body-set-auto-disable-flag
   :body-get-auto-disable-flag
   :body-set-auto-disable-time
   :body-get-auto-disable-time
   :body-set-auto-disable-steps
   :body-get-auto-disable-steps
   :body-set-auto-disable-average-samples-count
   :body-get-auto-disable-average-samples-count
   :body-set-auto-disable-angular-threshold
   :body-get-auto-disable-angular-threshold
   :body-set-auto-disable-linear-threshold
   :body-get-auto-disable-linear-threshold
   :world-set-max-angular-speed
   :world-get-max-angular-speed
   :world-set-damping
   :world-set-angular-damping
   :world-get-angular-damping
   :world-set-linear-damping
   :world-get-linear-damping
   :world-set-angular-damping-threshold
   :world-get-angular-damping-threshold
   :world-set-linear-damping-threshold
   :world-get-linear-damping-threshold
   :world-set-auto-disable-flag
   :world-get-auto-disable-flag
   :world-set-auto-disable-time
   :world-get-auto-disable-time
   :world-set-auto-disable-steps
   :world-get-auto-disable-steps
   :world-set-auto-disable-average-samples-count
   :world-get-auto-disable-average-samples-count
   :world-set-auto-disable-angular-threshold
   :world-get-auto-disable-angular-threshold
   :world-set-auto-disable-linear-threshold
   :world-get-auto-disable-linear-threshold
   :world-get-contact-surface-layer
   :world-set-contact-surface-layer
   :world-get-contact-max-correcting-vel
   :world-set-contact-max-correcting-vel
   :world-get-quick-step-w
   :world-set-quick-step-w
   :world-get-quick-step-num-iterations
   :world-set-quick-step-num-iterations
   :world-impulse-to-force
   :world-quick-step
   :world-step
   :world-set-step-threading-implementation
   :world-set-step-memory-manager
   :world-step-memory-functions-info
   :free-block
   :shrink-block
   :alloc-block
   :struct-size
   :world-step-memory-functions-info
   :world-set-step-memory-reservation-policy
   :world-step-reserve-info
   :reserve-minimum
   :reserve-factor
   :struct-size
   :world-step-reserve-info
   :worldstep-reservesize-default
   :worldstep-reservefactor-default
   :world-cleanup-working-memory
   :world-use-shared-working-memory
   :world-get-step-islands-processing-max-thread-count
   :world-set-step-islands-processing-max-thread-count
   :worldstep-threadcount-unlimited
   :world-get-cfm
   :world-set-cfm
   :world-get-erp
   :world-set-erp
   :world-get-gravity
   :world-set-gravity
   :world-get-data
   :world-set-data
   :world-destroy
   :world-create
   :i
   :c
   :mass
   :mass
   :mass-set-capped-cylinder-total
   :mass-set-capped-cylinder
   :mass-add
   :mass-rotate
   :mass-translate
   :mass-adjust
   :mass-set-trimesh-total
   :mass-set-trimesh
   :mass-set-box-total
   :mass-set-box
   :mass-set-cylinder-total
   :mass-set-cylinder
   :mass-set-capsule-total
   :mass-set-capsule
   :mass-set-sphere-total
   :mass-set-sphere
   :mass-set-parameters
   :mass-set-zero
   :mass-check
   :mass
   :remove-row-col
   :ldltremove
   :ldltadd-tl
   :solve-ldlt
   :vector-scale
   :solve-l1-t
   :solve-l1
   :factor-ldlt
   :is-positive-definite
   :invert-pdmatrix
   :solve-cholesky
   :factor-cholesky
   :multiply2
   :multiply1
   :multiply0
   :dot
   :set-value
   :set-zero
   :orthogonalize-r
   :plane-space
   :normalize4
   :normalize3
   :safe-normalize4
   :safe-normalize3
   :invert-matrix3
   :calc-matrix3-det
   :multiply-add2-333
   :multiply-add1-333
   :multiply-add0-333
   :multiply-add0-133
   :multiply-add1-331
   :multiply-add0-331
   :multiply2-333
   :multiply1-333
   :multiply0-333
   :multiply0-133
   :multiply1-331
   :multiply0-331
   :multiply-helper1-133
   :multiply-helper0-133
   :multiply-helper1-331
   :multiply-helper0-331
   :calc-points-distance3
   :set-cross-matrix-minus
   :set-cross-matrix-plus
   :subtract-vector-cross3
   :add-vector-cross3
   :calc-vector-cross3-444
   :calc-vector-cross3-441
   :calc-vector-cross3-414
   :calc-vector-cross3-411
   :calc-vector-cross3-144
   :calc-vector-cross3-141
   :calc-vector-cross3-114
   :calc-vector-cross3
   :calc-vector-dot3-44
   :calc-vector-dot3-41
   :calc-vector-dot3-14
   :calc-vector-dot3-33
   :calc-vector-dot3-31
   :calc-vector-dot3-13
   :calc-vector-dot3
   :calc-point-depth3
   :calc-vector-length-square3
   :calc-vector-length3
   :get-matrix-column3
   :copy-matrix4x3
   :copy-matrix4x4
   :copy-vector4
   :copy-negated-vector3
   :copy-scaled-vector3
   :copy-vector3
   :negate-vector3
   :scale-vector3
   :add-scaled-vectors3
   :subtract-vectors3
   :add-vectors3
   :message
   :debug
   :error
   :get-message-handler
   :get-debug-handler
   :get-error-handler
   :set-message-handler
   :set-debug-handler
   :set-error-handler
   :message-function
   :contact
   :fdir1
   :geom
   :surface
   :contact
   :contact-geom
   :side2
   :side1
   :g2
   :g1
   :epth
   :normal
   :pos
   :contact-geom
   :surface-parameters
   :slip2
   :slip1
   :motion-n
   :motion2
   :motion1
   :soft-cfm
   :soft-erp
   :bounce-vel
   :bounce
   :rho-n
   :rho2
   :rho
   :mu2
   :mu
   :mode
   :surface-parameters
   :contact-approx1
   :contact-approx1-n
   :contact-approx1-2
   :contact-approx1-1
   :contact-approx0
   :contact-rolling
   :contact-slip2
   :contact-slip1
   :contact-motion-n
   :contact-motion2
   :contact-motion1
   :contact-soft-cfm
   :contact-soft-erp
   :contact-bounce
   :contact-fdir1
   :contact-axis-dep
   :contact-mu2
   :close-ode
   :cleanup-odeall-data-for-thread
   :allocate-odedata-for-thread
   :allocate-odedata-flags
   :init-ode2
   :init-ode
   :init-odeflags
   :check-configuration
   :get-configuration
   :geom-get-body-next
   :geom-moved
   :joint-feedback
   :t2
   :f2
   :t1
   :f1
   :joint-feedback
   :transmission-chain-drive
   :transmission-intersecting-axes
   :transmission-parallel-axes
   :amotor-euler
   :amotor-user
   :param-group
   :param-erp3
   :param-suspension-cfm3
   :param-suspension-erp3
   :param-stop-cfm3
   :param-stop-erp3
   :param-cfm3
   :param-bounce3
   :param-fudge-factor3
   :param-fmax3
   :param-hi-vel3
   :param-lo-vel3
   :param-vel3
   :param-hi-stop3
   :param-lo-stop3
   :param-group3
   :param-erp2
   :param-suspension-cfm2
   :param-suspension-erp2
   :param-stop-cfm2
   :param-stop-erp2
   :param-cfm2
   :param-bounce2
   :param-fudge-factor2
   :param-fmax2
   :param-hi-vel2
   :param-lo-vel2
   :param-vel2
   :param-hi-stop2
   :param-lo-stop2
   :param-group2
   :param-erp1
   :param-suspension-cfm1
   :param-suspension-erp1
   :param-stop-cfm1
   :param-stop-erp1
   :param-cfm1
   :param-bounce1
   :param-fudge-factor1
   :param-fmax1
   :param-hi-vel1
   :param-lo-vel1
   :param-vel1
   :param-hi-stop1
   :param-lo-stop1
   :param-group1
   :params-in-group
   :param-erp
   :param-suspension-cfm
   :param-suspension-erp
   :param-stop-cfm
   :param-stop-erp
   :param-cfm
   :param-bounce
   :param-fudge-factor
   :param-fmax
   :param-hi-vel
   :param-lo-vel
   :param-vel
   :param-hi-stop
   :param-lo-stop
   :joint-type
   :-err-lcp
   :-err-uassert
   :-err-iassert
   :-err-unknown
   :world-step-threading-manager-id
   :joint-group-id
   :joint-id
   :geom-id
   :body-id
   :space-id
   :world-id
   :quaternion
   :matrix6
   :matrix4
   :matrix3
   :vector4
   :vector3
   :tri-index
   :real
   :uint8
   :int8
   :uint16
   :int16
   :uint32
   :int32
   :uint64
   :int64))
