(cl:in-package :clode)


(cffi:defctype real :float)

(cffi:defctype tri-tri-merge-callback :pointer)
(cffi:defctype tri-ray-callback :pointer)
(cffi:defctype tri-array-callback :pointer)
(cffi:defctype tri-callback :pointer)
(cffi:defctype tri-mesh-data-id :pointer)
(cffi:defctype aabbtest-fn :pointer)
(cffi:defctype geom-dtor-fn :pointer)
(cffi:defctype get-collider-fn-fn :pointer)
(cffi:defctype collider-fn :pointer)
(cffi:defctype get-aabbfn :pointer)
(cffi:defctype heightfield-get-height :pointer)
(cffi:defctype heightfield-data-id :pointer)
(cffi:defctype near-callback :pointer)
(cffi:defctype mass :pointer)
(cffi:defctype message-function :pointer)
(cffi:defctype world-step-threading-manager-id :pointer)
(cffi:defctype joint-group-id :pointer)
(cffi:defctype joint-id :pointer)
(cffi:defctype geom-id :pointer)
(cffi:defctype body-id :pointer)
(cffi:defctype space-id :pointer)
(cffi:defctype world-id :pointer)
(cffi:defctype quaternion :pointer)
(cffi:defctype matrix6 :pointer)
(cffi:defctype matrix4 :pointer)
(cffi:defctype matrix3 :pointer)
(cffi:defctype vector4 :pointer)
(cffi:defctype vector3 :pointer)
